apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: commerce-ops
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: commerce-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      labels:
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/part-of: commerce-ops
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:24.0.5
        args: ["start-dev", "--import-realm"]
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        volumeMounts:
        - name: realm
          mountPath: /opt/keycloak/data/import
          readOnly: true
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 40
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: "1"
            memory: 1Gi
      volumes:
      - name: realm
        configMap:
          name: keycloak-realm
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: commerce-ops
  labels:
    app.kubernetes.io/name: keycloak
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: keycloak
  ports:
  - name: http
    port: 8080
    targetPort: http
